[program:gtz]
command=/Users/g.alava/Sites/localhost/htmx/gtz-framework/start
autostart=true
autorestart=true
stderr_logfile=/var/log/myapp.err.log
stdout_logfile=/var/log/myapp.out.log

[supervisord]
nodaemon=true
